apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seraph-8/Helm-deployments.git
    targetRevision: MAIN
    path: capston
  destination:
    server: https://kubernetes.default.svc
    namespace: capstone
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
