apiVersion: v1
kind: Service
metadata:
  name: serahsmith-api
  labels:
    app: serahsmith-api
spec:
  type: CusterIP
  ports: 
  - port: 8080
    targetPort: 8080
  selector:
    app: serahsmith-api
