apiVersion: apps/v1
kind: Deployment
metadata:
  name:serahsmith -api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serahsmith-api
  template:
    metadata:
      labels:
        app: serahsmith-api
    spec:
      containers:
      - name: serahsmith-api
        image: "767398112260.dkr.ecr.us-east-1.amazonaws.com/serahsmith-api"
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "jdbc:postgresql://db:5432/postgres", "postgres", ""
        
        
       
  
