apiVersion: v1
kind: Service
metadata:
  name: serahsmith-api
  labels:
    app: serahsmith-api
spec:
  type: LoadBalancer
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: serahsmith-api
