apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsmith-api-deployment
  labels:
    app: wordsmith-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serahsmith-api
  template:
    metadata:
      labels:
        app: serahsmith-api
    spec:
      containers:
      - name: serahsmith-api
        image: "767398112260.dkr.ecr.us-east-1.amazonaws.com/serahsmith-api"
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "smith-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_NAME
          value: "serahsmith"

        
       
  
