apiVersion: v1
kind: Service
metadata:
  name: serasmith-db
  labels:
    app: serahsmith-db
spec:
  type: LoadBalancer
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: serahsmith-db
