# web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serahsmith-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serahsmith-web
  template:
    metadata:
      labels:
        app: serahsmith-web
    spec:
      containers:
      - name: serahsmith-web
        image: "767398112260.dkr.ecr.us-east-1.amazonaws.com/serahsmith-web"
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://wordsmith-api:8080"