apiVersion: v1
kind: Service
metadata:
  name:serahsmith-web
  labels:
    app:serahsmith-web
spec:
  type: LoadBalancer
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: serahsmith-web
